### Get all boards
GET http://localhost:5000/forum/boards
Accept: application/json

### Get a single board with threads
GET http://localhost:5000/forum/boards/1
Accept: application/json

### Create a new thread (without file)
POST http://localhost:5000/forum/threads
Content-Type: application/json

{
  "board_id": 1,
  "title": "Fascinating Black Hole Discovery",
  "content": "What do you think about the recent discovery of a supermassive black hole at the edge of our galaxy?"
}

### Get a thread with its comments
GET http://localhost:5000/forum/threads/1
Accept: application/json

### Add a comment to a thread
POST http://localhost:5000/forum/comments
Content-Type: application/json

{
  "thread_id": 1,
  "content": "I think this discovery challenges our current understanding of galactic formation."
}

### Notes:
# To test file uploads (images, videos, gifs), you'll need to use a tool like Postman 
# or create a frontend form that can handle multipart/form-data.

# For image upload:
 POST http://localhost:5000/forum/threads
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="board_id"
#
# 1
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="title"
#
# Thread with image
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="content"
#
# This is a thread with an image attachment
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="file"; filename="image.jpg"
# Content-Type: image/jpeg
#
# < ./image.jpg
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--